/*
 * @Date: 2023-08-14 09:52:44
 * @Description: description
 */
import { RouterMenus } from '@/types/index';
import { uniqueId } from 'lodash-es';

const asideMenuConfig: RouterMenus[] = [
  {
    id: uniqueId('three_'),
    name: "首页",
    path: "/home",
    icon: "HomeOutlined",
    component: "/Home",
    isHidden: false, /* 隐藏此菜单 */
    isParent: false,
  },
  {
    id: uniqueId('three_'),
    name: "第一个 3D 场景",
    path: "/first-scene",
    icon: "TableOutlined",
    component: "/FirstScene",
    isParent: false,
    auth: [], 
  },
  {
    id: uniqueId('three_'),
    name: "dat.gui 可视化调试",
    path: "/data-gui",
    icon: "TableOutlined",
    component: "/DataGui",
    isParent: false,
    auth: [], 
  },
  {
    id: uniqueId('three_'),
    name: "深入理解透视相机和视椎体",
    path: "/perspective-camera",
    icon: "TableOutlined",
    component: "/PerspectiveCamera",
    isParent: false,
    auth: [], 
  },
  {
    id: uniqueId('three_'),
    name: "BufferGeometry：顶点生成各种几何体",
    path: "/buffer-geometry",
    icon: "TableOutlined",
    component: "/BufferGeometry",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId('three_'),
    name: "点模型、线模型、网格模型",
    path: "/point-line-mesh",
    icon: "TableOutlined",
    component: "/PointLineMesh",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId('three_'),
    name: "实战：随机山脉地形",
    path: "/mountain-terrain",
    icon: "TableOutlined",
    component: "/MountainTerrain",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId('three_'),
    name: "材质颜色和纹理贴图",
    path: "/material-color-texture",
    icon: "TableOutlined",
    component: "/MaterialColorTexture",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId('three_'),
    name: "uv 坐标和 uv 动画",
    path: "/texture-uv",
    icon: "TableOutlined",
    component: "/TextureUv",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId('three_'),
    name: "如何画各种曲线",
    path: "/curve",
    icon: "TableOutlined",
    component: "/Curve",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId('three_'),
    name: "按照规律生成各种几何体",
    path: "/generate-geometry",
    icon: "TableOutlined",
    component: "/GenerateGeometry",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId('three_'),
    name: "实战：隧道穿梭",
    path: "/tube-travel",
    icon: "TableOutlined",
    component: "/TubeTravel",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId('three_'),
    name: "uv 动画实战：无限时空隧道",
    path: "/infinite-tunnel",
    icon: "TableOutlined",
    component: "/InfiniteTunnel",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId('three_'),
    name: "实战：盖房子",
    path: "/house",
    icon: "TableOutlined",
    component: "/House",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId('three_'),
    name: "场景遍历和世界坐标",
    path: "/scene-group",
    icon: "TableOutlined",
    component: "/SceneGroup",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId('three_'),
    name: "各种灯光和常用 Helper",
    path: "/light-helper",
    icon: "TableOutlined",
    component: "/LightHelper",
    isParent: false,
    auth: [],
  },
];
console.log(asideMenuConfig, 46);
export { asideMenuConfig };
