/*
 * @Date: 2023-08-14 09:52:44
 * @Description: description
 */
import { RouterMenus } from "@/types/index";
import { uniqueId } from "lodash-es";

const asideMenuConfig: RouterMenus[] = [
  {
    id: uniqueId("three_"),
    name: "首页",
    path: "/home",
    icon: "HomeOutlined",
    component: "/Home",
    isHidden: false /* 隐藏此菜单 */,
    isParent: false,
  },
  {
    id: uniqueId("three_"),
    name: "第一个 3D 场景",
    path: "/first-scene",
    icon: "TableOutlined",
    component: "/FirstScene",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "dat.gui 可视化调试",
    path: "/data-gui",
    icon: "TableOutlined",
    component: "/DataGui",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "深入理解透视相机和视椎体",
    path: "/perspective-camera",
    icon: "TableOutlined",
    component: "/PerspectiveCamera",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "BufferGeometry：顶点生成各种几何体",
    path: "/buffer-geometry",
    icon: "TableOutlined",
    component: "/BufferGeometry",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "点模型、线模型、网格模型",
    path: "/point-line-mesh",
    icon: "TableOutlined",
    component: "/PointLineMesh",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "实战：随机山脉地形",
    path: "/mountain-terrain",
    icon: "TableOutlined",
    component: "/MountainTerrain",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "材质颜色和纹理贴图",
    path: "/material-color-texture",
    icon: "TableOutlined",
    component: "/MaterialColorTexture",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "uv 坐标和 uv 动画",
    path: "/texture-uv",
    icon: "TableOutlined",
    component: "/TextureUv",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "如何画各种曲线",
    path: "/curve",
    icon: "TableOutlined",
    component: "/Curve",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "按照规律生成各种几何体",
    path: "/generate-geometry",
    icon: "TableOutlined",
    component: "/GenerateGeometry",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "实战：隧道穿梭",
    path: "/tube-travel",
    icon: "TableOutlined",
    component: "/TubeTravel",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "uv 动画实战：无限时空隧道",
    path: "/infinite-tunnel",
    icon: "TableOutlined",
    component: "/InfiniteTunnel",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "实战：盖房子",
    path: "/house",
    icon: "TableOutlined",
    component: "/House",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "场景遍历和世界坐标",
    path: "/scene-group",
    icon: "TableOutlined",
    component: "/SceneGroup",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "各种灯光和常用 Helper",
    path: "/light-helper",
    icon: "TableOutlined",
    component: "/LightHelper",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "顶点法线和反射原理",
    path: "/vertex-normal",
    icon: "TableOutlined",
    component: "/VertexNormal",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "自定义顶点颜色实现渐变",
    path: "/geometry-color",
    icon: "TableOutlined",
    component: "/GeometryColor",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "实战：颜色渐变柱状图",
    path: "/gradient-color-bar-chart",
    icon: "TableOutlined",
    component: "/GradientColorBarChart",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "如何加载外部模型",
    path: "/gltf-model",
    icon: "TableOutlined",
    component: "/GltfModel",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "GLTF 的三种文件结构",
    path: "/gltf-structure",
    icon: "TableOutlined",
    component: "/GltfStructure",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "gltf-pipeline：处理 gltf 模型的工具",
    path: "/gltf-pipeline-test",
    icon: "TableOutlined",
    component: "/GltfPipelineTest",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "Draco：压缩 gltf 模型，提升性能",
    path: "/gltf-draco-test",
    icon: "TableOutlined",
    component: "/GltfDracoTest",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "包围盒与模型大小计算",
    path: "/box3-test",
    icon: "TableOutlined",
    component: "/Box3Test",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "包围盒 Box3 常用 api",
    path: "/box3-api",
    icon: "TableOutlined",
    component: "/Box3Api",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "正投影相机和三种灯光的阴影",
    path: "/orthographic-camera-shadow",
    icon: "TableOutlined",
    component: "/OrthographicCameraShadow",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "OrbitControls 的常用属性方法",
    path: "/orbit-controls",
    icon: "TableOutlined",
    component: "/OrbitControls",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "射线与点击选中 3D 场景物体",
    path: "/ray-caster",
    icon: "TableOutlined",
    component: "/RayCaster",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "后期处理与描边发光效果",
    path: "/post-processing",
    icon: "TableOutlined",
    component: "/PostProcessing",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "各种后期处理效果",
    path: "/all-pass",
    icon: "TableOutlined",
    component: "/AllPass",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "精灵模型 Sprite 和下雨下雪效果",
    path: "/sprite",
    icon: "TableOutlined",
    component: "/Sprite",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "实战：林海雪原",
    path: "/snowy-forest",
    icon: "TableOutlined",
    component: "/SnowyForest",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "几何体材质共用和 clone、copy",
    path: "/material-share",
    icon: "TableOutlined",
    component: "/MaterialShare",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "补间动画库 Tween.js",
    path: "/tween-animation",
    icon: "TableOutlined",
    component: "/TweenAnimation",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "Tween.js 常用 API",
    path: "/tween-all-feature",
    icon: "TableOutlined",
    component: "/TweenAllFeature",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "关键帧动画和模型动画播放",
    path: "/keyframes-animation",
    icon: "TableOutlined",
    component: "/KeyframesAnimation",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "实战：丝滑入场动画",
    path: "/tube-entry-animation",
    icon: "TableOutlined",
    component: "/TubeEntryAnimation",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "改变顶点的变形动画",
    path: "/morph-animation",
    icon: "TableOutlined",
    component: "/MorphAnimation",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "骨骼动画：关节带动顶点运动",
    path: "/bone-animation",
    icon: "TableOutlined",
    component: "/BoneAnimation",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "GSAP：另一个常用动画库",
    path: "/gsap-test",
    icon: "TableOutlined",
    component: "/GsapTest",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "CSS2DRenderer 实现标注：给 3D 物体加标签",
    path: "/css2d-annotation",
    icon: "TableOutlined",
    component: "/Css2dAnnotation",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "CSS3DRenderer 实现标注：公告栏内容",
    path: "/css3d-annotation",
    icon: "TableOutlined",
    component: "/Css3dAnnotation",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "Sprite 结合 canvas 实现各种形状的标注",
    path: "/canvas-sprite-annotation",
    icon: "TableOutlined",
    component: "/CanvasSpriteAnnotation",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "Canvas 画各种图案作为纹理",
    path: "/canvas-texture",
    icon: "TableOutlined",
    component: "/CanvasTexture",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "SpriteText：开箱即用的文字组件",
    path: "/sprite-text-test",
    icon: "TableOutlined",
    component: "/SpriteTextTest",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "实战：数字雨",
    path: "/number-rain",
    icon: "TableOutlined",
    component: "/NumberRain",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "实战：3D 饼图",
    path: "/3d-pie-chart",
    icon: "TableOutlined",
    component: "/PieChart",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "3D 场景如何加入音频",
    path: "/audio-api",
    icon: "TableOutlined",
    component: "/AudioApi",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "实战：双人斗舞",
    path: "/two-dancer",
    icon: "TableOutlined",
    component: "/TwoDancer",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "音乐频谱可视化",
    path: "/audio-analyser",
    icon: "TableOutlined",
    component: "/AudioAnalyser",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "PBR 材质：逼真的金属、塑料、磨砂效果",
    path: "/pbr-material",
    icon: "TableOutlined",
    component: "/PbrMaterial",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "PBR 材质：逼真的金属、塑料、磨砂效果",
    path: "/car-config",
    icon: "TableOutlined",
    component: "/CarConfig",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "MatCap 材质：通过光照球实现伪光照效果",
    path: "/matcap-material",
    icon: "TableOutlined",
    component: "/MatcapMaterial",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "HDR：亮度范围更广的全景图",
    path: "/hdr-background",
    icon: "TableOutlined",
    component: "/HdrBackground",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "CubeCamera 实现镜子效果",
    path: "/cube-camera-envmap",
    icon: "TableOutlined",
    component: "/CubeCameraEnvmap",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "Reflector 实现镜子效果",
    path: "/reflector-mirror",
    icon: "TableOutlined",
    component: "/ReflectorMirror",
    isParent: false,
    auth: [],
  },
  {
    id: uniqueId("three_"),
    name: "向量点积实现锐角判断",
    path: "/vector-dot",
    icon: "TableOutlined",
    component: "/VectorDot",
    isParent: false,
    auth: [],
  },
];
console.log(asideMenuConfig, 46);
export { asideMenuConfig };

// version: '3'

// services:
//   nginx:
//     image: nginx:latest
//     ports:
//       - "80:80"
//       - "443:443"
//     volumes:
//       - ./nginx/certs:/etc/nginx/certs
//       - ./nginx/conf.d:/etc/nginx/conf.d
//       - /workspace/html:/usr/share/nginx/html
//     restart: always
